version: '3.8'

services:
  mongopersonal:
    build: 
      context: .
      dockerfile: Dockerfilemongo
        # image: mongo:latest
        #    restart: always
    ports:
      - 27017:27017
    networks:
      - default
      - nttdata-net
  personalapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - "mongopersonal"
    networks:
      - default
      - nttdata-net
networks:
  default: 
    driver: bridge
  nttdata-net:
    external: true

